### PR TITLE
[Refactor] Move ConsoleHelper to its own file

### PR DESCRIPTION
**Pull request by scowalt**
Also deleted `ConsoleCopy`

### CODE REVIEW

**Comment by scowalt** [comment]
It's possible `ConsoleHelper` should come along with this. I'm also not entirely confident this will build with the other projects.

**Comment by NarryG** [comment]
> It's possible `ConsoleHelper` should come along with this. I'm also not entirely confident this will build with the other projects.

Individual emulators shouldn't be spawning the console manually using ConsoleCopy, they should be using ConsoleHelper. I don't think moving ConsoleHelper to its own file will cause any issues as long as you don't touch the namespace.

**Comment by scowalt** [comment]
Looks like `ConsoleCopy` isn't even used anywhere (CI will validate that). I moved `ConsoleHelper` to its own file and deleted `ConsoleCopy` entirely.

**Comment by NarryG** [comment]
I may have gotten rid of the need for ConsoleCopy when I added in NLog. We'll see if CI fails for anything. I can't remember if I used it in anything.

**Pull request merged**
