### PR TITLE
Fix Disposable classes

### PR DESCRIPTION
**Pull request by scowalt**
- Fixes CA1001: Class owns disposable fields but is not disposable
- Fixes CA2213: Change Dispose method to call Close or Dispose on member

Bizhawk and CemuStub build with this change.

The `Form` classes have their `Dispose` implementation in generated code. (The `.designer.cs` files) So I've disabled the rule for these files.

### CODE REVIEW

**Comment by NarryG** [comment]
The designer is just going to end up changing all of these back the next time we touch the form, so that's probably a no-go. Honestly, if it's designer generated code, I think it's better off just excluding it from the rules. I'm guessing there's a way to do that.

**Comment by scowalt** [comment]
Okay, thanks for that context, that's what I feared.

Let me spend some more time investigating to see if I can come up with a better solution that *doesn't* touch generated files. If not, I'll just exclude it member of the `Form`s classes from the rule.

**Comment by scowalt** [comment]
It appears the correct solution here is to move the `Dispose` implementation from the `.designer.cs` file to the `.cs` file. This will prevent the designer from overwriting changes if the files are regenerated.
- [Stackoverflow answer from 2009/2015](https://stackoverflow.com/a/1052186)
- [Stackoverflow answer from 2014](https://stackoverflow.com/a/23690773)
- [Stackoverflow answer from 2015](https://stackoverflow.com/a/30172789)
- [Stackoverflow answer from 2010](https://stackoverflow.com/a/3832914)

I'll update this PR to move the `Dispose` implementations

**Comment by NarryG** [comment]
I'm not really a huge fan of this workaround, mainly because we'll have to apply the fix to any new forms in the future and the designer-generated code doesn't abide by "modern" standards in the first place. As you go through the rules, I expect you'll run into a lot more designer violations. It's generated code, trying to clean it up is futile in my opinion.

I'd honestly just exclude .designer.cs files from style rules as this won't be the first instance of "designer designed 20 years ago doesn't generate modern code".

**Comment by scowalt** [comment]
That's fair.

These issues appear in the `.cs` files, not the `.designer.cs` files. However, I could see the argument for disabling these warnings in files where the warnings are caused by designer-generated files.

**Pull request merged**
