### PR TITLE
Add DependaBot to repository

### PR DESCRIPTION
**Pull request by scowalt**
Check out the pull requests on my fork for an example of what this looks like https://github.com/scowalt/RTCV/pulls

Curious if this type of automated dependency tracking is something we want to implement

### CODE REVIEW

**Comment by NarryG** [comment]
While Dependabot is nice, there are some dependency restrictions for compatibility reasons. I'd assume you can just deny the PR and the bot will not poke you again?

**Comment by scowalt** [comment]
Better, we should be able to add those dependencies to the yml file. The bot won't bug us about that dependency in the first place.

If you let me know which ones can't be updated I can add them to the yml

**Comment by NarryG** [comment]
> Better, we should be able to add those dependencies to the yml file. The bot won't bug us about that dependency in the first place.
> 
> If you let me know which ones can't be updated I can add them to the yml
> 
> More info: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#ignore

Both Ceras and System.Composition (MEF, the plugin host) require usage of System.Runtime.CompilerServices.Unsafe. Ceras gets upset if you go too new with the version of the library, so PluginHost is set up to use the version of the library that Ceras uses, despite there being newer versions. I don't think there are any other conflicts at the moment.

**Comment by scowalt** [comment]
Done. Added `System.Runtime.CompilerServices.Unsafe` to exceptions. I'm not 100% sure this will work, but we can always update this config and we have the option of manually closing + ignoring pull requests.

**Comment by NarryG** [comment]
We can see how this goes and if it gets annoying/breaks things, revert as needed.

**Pull request merged**
