### PR TITLE
[Cleanup] Minor CorruptCore cleanup and refactor

### PR DESCRIPTION
**Pull request by scowalt**
This change is a refactoring change. Mostly just to address IDE/analyzer warnings.

I disabled `dotnet_naming_style.static_field_style.required_prefix` since it's not being followed in any files that I've found.

I created a helper function `GetIntensity` to refactor out a small chunk of code.

### CODE REVIEW

**Comment by NarryG** [comment]
I need to verify this one against the CPP implementations to ensure there's no conflicts. If I'm not mistaken, they use those properties. Similar to other issues, I don't have the time at the moment to do the mass updates. I'll tackle all of those at once.

**Comment by scowalt** [comment]
Are these other implementations open source? I could work to validate them myself, and/or add them to CI for automatic validation

**Comment by NarryG** [comment]
C#
https://github.com/ircluzar/FileStub-Vanguard
https://github.com/ircluzar/UnityStub-Vanguard
https://github.com/NarryG/ProcessStub-Vanguard

C++ (cmake > sln)
https://github.com/NarryG/citra-vanguard (may not compile from a fresh pull as I had to make a one-line change to a dependency that was submodule'd and I haven't pushed my own submodule fork)
https://github.com/NarryG/melonDS-Vanguard (needs SDL2 and certain header files which aren't in the repo to build under MSVC)

C++ (comes with sln)
https://github.com/NarryG/dolphin-vanguard 
https://github.com/NarryG/pcsx2-Vanguard (Needs some older deps  & MSVC 2017 instead of 2019)  

Building the C++ ones is an absolute mess at the moment. I doubt you'll be able to get some of them building under github actions without a _lot_ of work.  I want to look into submoduling things on git at some point to clean things

**Comment by scowalt** [comment]
Thanks! This is something I can try to chip away at at some point

**Comment by scowalt** [comment]
I'm working on getting all of these into CI so that these will be automatically validated. At time of writing, I've done:

- FileStub-Vanguard
- UnityStub-Vanguard
- ProcessStub-Vanguard
- Dolphin-vanguard
- pcsx2-Vanguard

The `cmake` projects have been painful to work with, but I'm hoping to find a solution for those soon.

**Comment by scowalt** [comment]
PR #42 will add automatic validation to everything except `citra-vanguard` and `melonDS-Vanguard`. Those will need to be validated manually until I can figure out how to get those to play nicely in CI.

**Comment by NarryG** [comment]
Various conflicts due to the objects refactor.

**Comment by scowalt** [comment]
Merge conflicts resolved 😄

**Comment by NarryG** [comment]
Looks like some conflicts snuck back in since. Now that the CI commit is in place this should be good once that's resolved.

**Pull request merged**
