### PR TITLE
Remove CustomException, fix rules

### PR DESCRIPTION
**Pull request by scowalt**
Fix `CA1032` and `CA2237` by removing `CustomException` and fixing `AbortEverythingException`

### CODE REVIEW

**Comment by NarryG** [comment]
Both of these exception types can probably be refactored out anyways. I can merge this in, or if you feel like just replacing all instances of CustomException and AbortEverythingException with Exception e, feel free.
They're left-over from an older version of the exception handler, and as of this point in time, they don't provide anything over `Exception`. The exception handler used to use these types when determining the options to provide (CustomException stated that it was coming from specific parts of the RTC, AbortEverythingException forced you to quit).

**Comment by scowalt** [comment]
I might as well refactor out all of these old exception types while I'm here.

**Comment by scowalt** [comment]
Removing the old exception type will require a simultaneous fix in Bizhawk_Vanguard. I'll work on that and link the PR in the description.

**Comment by scowalt** [comment]
This can safely be pulled in once [this PR](https://github.com/ircluzar/Bizhawk-Vanguard/pull/10) is merged into Bizhawk-Vanguard. Until then, I'll leave this as a draft.

**Comment by NarryG** [comment]
See https://github.com/ircluzar/Bizhawk-Vanguard/pull/10#pullrequestreview-433770022

**Comment by scowalt** [comment]
Yep! I'll leave the `AbortEverythingException` type in. I believe the `CustomException` type can still be removed.

**Pull request merged**
