### PR TITLE
Remove dead StringExtensions code, misc cleanup

### PR DESCRIPTION
**Pull request by scowalt**
The `StringExtensions` classes in the UI Controls and the HexEditor plugin had a bunch of dead code. I removed what I could, and replaced what I could with functions built-in to the dotnet libraries.

I also touched most of the files in `Source/Frontend/UI/Components/Controls` to do some minor cleanup.

### CODE REVIEW

**Comment by NarryG** [comment]
Personally, I think having a common extension class for string/char is more usable than the built in URI check for chars, mainly because there's no built-in string check. It just needs to be made consistent as there's instances of checking for valid hex all over the codebase using local methods.  
Could you refactor the string & char IsHex into an extension method in Common instead? Then we can go through the codebase and scan for instances of hex checks and consolidate them to all be done the same way.

**Comment by scowalt** [comment]
Agreed! I'm using the common extension class approach in my newer PR and I like that better. I'll revisit and rewrite this one.

**Comment by NarryG** [comment]
Sounds good. There's a lot of things that live in the _Extensions classes in the various libraries (especially Netcore) that'd make  sense to be refactored into Common now that it exists. For a while we just coasted on the fact that everything was imported, but as we move to try and clean up the amount of public methods (there's way too much public code that leads to fun mistakes), refactoring common helpers into Common is a good idea.

**Comment by scowalt** [comment]
Replaced this with #51

**Pull request closed without merging**
