### PR TITLE
[Refactor] RTCV.NetCore.NetCore_Extensions is now a namespace instead of a class

### PR DESCRIPTION
**Pull request by scowalt**
I was trying to fix `CA1034`. During this investigation, I noticed that the class `RTCV.NetCore.NetCore_Extensions` was just acting as a static holder for helper methods, which would be better suited as a `namespace`.

This change converts `RTCV.NetCore.NetCore_Extensions` into a `namespace`. I've also deleted a little bit of dead code and made minor changes to various methods. This change should have no functional differences.

[This change requires a simultaneous fix in BizHawk_Vanguard](https://github.com/ircluzar/Bizhawk-Vanguard/pull/11). I manually validated that `CemuStub-Vanguard` will build with this change.

### CODE REVIEW

**Comment by NarryG** [comment]
Holding off on this one as the various other stubs & the c++ emulators may need fixes as well and I don't have time to run the update at the moment. I'm fine with this change, I just don't have the time to do all those updates right now.

**Comment by NarryG** [comment]
Various conflicts due to other refactors.

**Comment by scowalt** [comment]
Merge conflicts are resolved (reminder that this still breaks BizHawk-Vanguard, thus the build failure)

**Comment by NarryG** [comment]
Can you rebase this/update your branch so github pulls in the new actions?

**Comment by scowalt** [comment]
Done, new actions are running

**Pull request merged**
