### PR TITLE
[CI] Expanded Github CI to include more dependants

### PR DESCRIPTION
**Pull request by scowalt**
Added the following projects to CI:
- FileStub-Vanguard
- UnityStub-Vanguard
- ProcessStub-Vanguard
- [melonDS-Vanguard](https://github.com/NarryG/melonDS-Vanguard/pull/1)
- [dolphin-vanguard](https://github.com/NarryG/dolphin-vanguard/pull/1)
- [pcsx2-Vanguard](https://github.com/NarryG/pcsx2-Vanguard/pull/2)
- [citra-vanguard](https://github.com/NarryG/citra-vanguard/pull/2)

Previously working in CI:
- Bizhawk-Vanguard
- CemuStub-Vanguard

### CODE REVIEW

**Comment by scowalt** [comment]
Hey, that looks pretty nice!
image

**Comment by NarryG** [comment]
image
image

Looks like it's not building all the projects in the right config.

**Comment by scowalt** [comment]
Oh! Good catch! I can take this back to the drawing board to fix that

**Comment by scowalt** [comment]
Dolphin, unfortunately, won't build in Github CI. [See the error from this build log](https://github.com/scowalt/dolphin-vanguard/runs/822650148?check_suite_focus=true):

> d:\a\dolphin-vanguard\dolphin-vanguard\dolphin-vanguard\externals\gtest\src\gtest-all.cc: fatal error C1853: 'D:\a\dolphin-vanguard\dolphin-vanguard\dolphin-vanguard\Source\..\Build\x64\Debug\pch\pch.pch' precompiled header file is from a previous version of the compiler, or the precompiled header is C++ and you are using it from C (or vice versa)

There are lots of these "precompiled header from previous version" errors. My guess is that since Github CI is using the latest version of MSBuild, there is a version mismatch with the precompiled headers.

I might be able to use a different CI service or setup a docker image to build dolphin. For now, I'll have to remove it from this change.

Still investigating PCSX2, but I expect a similar result.

**Comment by scowalt** [comment]
[PCSX2 has some build errors that suggest the repo may be in a broken state](https://github.com/scowalt/pcsx2-Vanguard/runs/822653725?check_suite_focus=true):

> "D:\a\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2-Vanguard\PCSX2_suite.sln" (default target) (1) ->
"D:\a\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2\WINDOWS\VCprojects\pcsx2.vcxproj" (default target) (2) ->
(ClCompile target) -> 
  d:\a\pcsx2-vanguard\pcsx2-vanguard\pcsx2-vanguard\pcsx2\vanguard\vanguardclient.cpp(658): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "PrecompiledHeader.h"' to your source? [D:\a\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2\WINDOWS\VCprojects\pcsx2.vcxproj]
  c1xx : fatal error C1083: Cannot open source file: '..\..\Vanguard\UnmanagedWrapper.cpp': No such file or directory [D:\a\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2\WINDOWS\VCprojects\pcsx2.vcxproj]
  d:\a\pcsx2-vanguard\pcsx2-vanguard\pcsx2-vanguard\pcsx2\vanguard\pcsx2memorydomain.cpp(64): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "PrecompiledHeader.h"' to your source? [D:\a\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2-Vanguard\pcsx2\WINDOWS\VCprojects\pcsx2.vcxproj]

Either way, I probably won't be able to get this working anytime soon. I'll remove it from this change.

**Comment by scowalt** [comment]
Update: it should be possible for us to validate all of these projects in CI! See the PR description for details.

**Comment by NarryG** [comment]
Had a few issues with the implementations on the other repos. See those comments. I'm still 100% on board for this, but I'm currently very busy with a different project so I haven't been anywhere near as responsive as normal at the moment. Apologies on the delays!

**Comment by scowalt** [comment]
No worries, best of luck with your new project! (I can't wait to see it! 😄 )

I'll follow-up with the implementations I need to make in the other repos, and modify the PR to include the repos that are now ready to go.

**Comment by NarryG** [comment]
Now that ViH is over and I'm not handcuffed to Unity working on Vine Realms, I'm going to take a look at all of these PRs and attempt to get them all merged in. Might take a few days simply due to the volume of stuff I have to catch up on. Thanks again for the patience.

**Comment by scowalt** [comment]
No worries! Thanks for taking a look at all of this stuff 😄

**Comment by NarryG** [comment]
Looks like this is all set to me?

**Comment by scowalt** [comment]
Yes, it should be! I would wait for the current actions to finish to make sure I didn't mess anything up copy+pasting the `citra` script.

Should only take like 20 minutes 😅

**Comment by scowalt** [comment]
Done! This is passing and ready to be merged

**Comment by scowalt** [comment]
🎉🎉🎉

Thanks for all of your help on this one Narry. I'm really excited about and proud of this change 😁

**Comment by NarryG** [comment]
Up next is making it more maintainable by re-orging the branches 😛

**Comment by scowalt** [comment]
Yes! The dev/main -> beta -> stable pipeline will be another big organization win

**Pull request merged**
